---

antora:
  name: modules
  dir: www
  modules:
  - name: 01-intro
    label: Intro to the Laboratory
    solveButton: false
  - name: 02-dashboard
    label: 1.0 - Exploring the web-UI and Dashboard
    solveButton: false
  - name: 03-inventory
    label: 1.1 - Creating an Inventory
    solveButton: true
  - name: 04-project
    label: 1.2 - Creating your first Project
    solveButton: true
  - name: 05-credentials
    label: 1.3 - Get to know Credentials
    solveButton: false
  - name: 06-template
    label: 1.4 - Creating a Job Template
    solveButton: true
  - name: 07-project-additional
    label: 1.5 - Creating a second Project
    solveButton: true
  - name: 08-template-extended
    label: 1.6 - Creating a second and third Job Templates
    solveButton: true
  - name: 09-workflow
    label: 1.7 - Creating a Workflow Job Template
    solveButton: true
  - name: 10-template-survey
    label: '1.8 - BONUS: Creating a Job Template with a Survey'
    solveButton: true
  - name: 11-recap-review
    label: Recap and review
    solveButton: false

tabs:
- name: ">_ Controller CLI"
  url: /wetty
- name: VSCode Editor
  url: https://control-${guid}.${domain}/editor/?folder=/home/rhel/
