---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Itroduction to ansible-builder"
      solveButton: false
    - name: module-02
      label: "Let's create a basic execution environment"
      solveButton: false
    - name: module-03
      label: "Let's create an execution environment with collection from automation hub"
      solveButton: false
    - name: module-04
      label: "Fix the SSL errors while building execution environment"
      solveButton: false
    - name: module-05
      label: "Remove token from ansible.cfg file and build EE again"
      solveButton: false


tabs:
  - name: AAP
    url: https://control-${guid}.${domain}/
    external: false
  - name: VS Code
    url: https://vscode-${guid}.${domain}
    external: true
